title: "The Adventures of Sherlock Holmes"
subtitle: "Published with Guten"
author: "Arthur Conan Doyle"
publish_date: "Oct 14, 1892"

lang: "en"

baseurl: "/guten"
markdown: kramdown

collections:
    chapters:
        output: true

defaults:
    -
        scope:
            path: ""
            type: "chapters"
        values:
            layout: "chapter"

exclude:
    - Gemfile
    - Gemfile.lock
